{% set name = "scramaligner" %}
{% set version = "2.0.5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # path: /repo/scramaligner/scramAligner
  url: https://github.com/sfletc/scramAligner/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e693df70f5f5d0c236f64f5de905b4b12cd6c23bf92fec9f1720b0bb162b5883

build:
  number: 0
  # skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('go') }}
    - make
    - {{ compiler('c') }}

  host:
    - python>=3.7
    - pip

  run:
    - python>=3.7
    - matplotlib-base
    - seaborn
    - numpy-base
    - pandas

test:
  commands:
    - scram2 --help
    - scram2Plot --help

about:
  home: https://github.com/sfletc/scramAligner
  license: BSD-3
  license_family: BSD
  license_file: LICENSE
  summary: ScramAligner is a bioinformatics packages that trims small RNA read adapters, aligns small RNA reads and plots the alignments.
