{% set name = "scramaligner" %}
{% set version = "2.0.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  # path: /repo/scramaligner/scramAligner
  url: https://github.com/sfletc/scramAligner/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b751b60c69a0bc2997fc1040ac7e4f84fe728a6a0bf847f4eb4c7a53571be0b8

build:
  number: 0
  # skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('go') }}
    - make
    - {{ compiler('c') }}

  host:
    - python>=3.7
    - pip

  run:
    - python>=3.7
    - matplotlib-base
    - seaborn
    - numpy>=1.23
    - pandas

test:
  commands:
    - scramAligner --help
    - adaptTrim --help
    - scram2Plot --help

about:
  home: https://github.com/username/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A bioinformatics application combining Go and Python scripts
  description: |
    This application is a bioinformatics tool that combines a Go-based app and Python scripts for processing and analyzing biological data. It utilizes the Go programming language for the main application and Python scripts for additional functionality.
  doc_url: https://github.com/username/{{ name }}/wiki
  dev_url: https://github.com/username/{{ name }}/issues

extra:
  identifiers:
    - doi:your_doi_here
    - pmid:your_pmid_here